### ISSUE TITLE
Meta.profile in Körpergewicht und (ggf. in Herzfrequenz)

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiK-Vitalparameter-und-Koerpermasse#131]
https://github.com/gematik/spec-ISiK-Vitalparameter-und-Koerpermasze/blob/fc1f25db959cc1cc337b289f6a53d55315b25fa5/Resources/input/fsh/ISiK-Koerpergewicht.fsh#L22C1-L23C97

Es besteht eine Inkonsistenz beim VS-Binding bei den angegebenen Meta.profilen

Welche Funktion haben diese Meta.profile

analog in [ISiK-Herzfrequenz.fsh](https://github.com/gematik/spec-ISiK-Vitalparameter-und-Koerpermasze/blob/main-stufe-3/Resources/input/fsh/ISiK-Herzfrequenz.fsh)

FYI @alexey-tschudnowsky 
```[tasklist]
### Tasks
- [x] PTDATA-713
```

**Comment by f-peverali** [comment]
@ylboerner was denkst du dazu?

**Comment by ylboerner** [comment]
@f-peverali Die `meta.profile` Felder kennzeichnen eine Adhärenz des Beispiels zu dem internationalen sowie deutschen (Basisprofile) Profil für das Körpergewicht. Einfach gesagt: "Dieses Beispiel ist auch konform zum internationalen und deutschen Körpergewicht Profil". Eine Anpassung ist meiner Meinung nach nicht nötig, da das ISiK Profil auch mit in der Instanz hinterlegt ist: 

```
"meta": {
    "profile": [
      "https://gematik.de/fhir/isik/v3/VitalparameterUndKoerpermasze/StructureDefinition/ISiKKoerpergewicht",
      "http://hl7.org/fhir/StructureDefinition/bodyweight",
      "http://fhir.de/StructureDefinition/observation-de-vitalsign-koerpergewicht"
    ]
  },
```

**Comment by f-peverali** [comment]
@alexey-tschudnowsky könntest Du mir hier nochmal helfen? Bei welchem Element besteht die Inkonsistenz beim VS-Binding?

**Comment by ylboerner** [comment]
@f-peverali Alles korrekt, daher schließe ich diesen Issue. Falls wir noch weitere Erläuterungen bezüglich dem inkonsistenten VS-Binding erhalten, machen wir einen neuen Issue auf.
