### ISSUE TITLE
🐛 [BUG] - Pattern auf coding Element in Blutdruck Profil

### ISSUE THREAD

**Issue by ylboerner** [gematik/spec-ISiK-Vitalparameter-und-Koerpermasse#132]
### Description

Das Pattern auf `code.coding` verhindert die Kodierung mittels anderer Terminologien. Das Pattern darf nur auf `code` existieren oder in einem `coding` Slice für LOINC.

### Reproduction URL

https://simplifier.net/isik-vitalparameter-und-koerpermasze-v3/isikblutdruck

### Reproduction Steps

```bash
N/A
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by f-peverali** [comment]
@ylboerner das stammt aus den basisprofilen, richtig? ggf. gleich dort klären?

**Comment by patrick-werner** [comment]
mittlerweile behoben
