### ISSUE TITLE
💡 [REQUEST] - ISiKGCS Komponenten sollten dataAbsentReason erlauben

### ISSUE THREAD

**Issue by ylboerner** [gematik/spec-ISiK-Vitalparameter-und-Koerpermasse#133]
### Summary

In manchen Daten exisiteren GCS Observations bei denen die einzelnen Werte (Eye, Motor & Verbal) nicht explizit vorhanden sind, sondern nur die Summe dieser Werte dokumentiert wurde.

Im Profil ISiKGCS ist das value Feld der drei Slices jedoch mit einer 1*1 Kardinalität definiert. Dies verhindert das Nutzen des dataAbsentReason Feldes um die Abwesenheit der Datenfelder ausdrücken zu können.

**Todo: DataAbsentReason auf MS und value auf 0..1 setzen und die aktuellen Constraints belassen.** 

### Common Examples

Falls Systeme nur GCS als Ganzes betrachten und nicht in einzelne Werte zerlegen.

**Comment by ylboerner** [comment]
@f-peverali Hier der passende Issue für ANFISK-169 👍

**Comment by patrick-werner** [comment]
Nach interner Diskussion:
- alle 3 components sind nun explizit MS
- alle components haben nun die Kardinalität von 0..1 (können also weggelassen werden)

**Comment by alexzautke** [comment]
Fixed by https://github.com/gematik/spec-ISiK-Vitalparameter-und-Koerpermasze/pull/138
