### ISSUE TITLE
ISIKPatient und ISiKKontaktGesundheitseinrichtung als zu unterstützende Profile

### ISSUE THREAD

**Issue by alexey-tschudnowsky** [gematik/spec-ISiK-Vitalparameter-und-Koerpermasse#139]
### Summary

Patient und Encounter-Ressourcen werden in den Referenzen der Vitalmodul-Profile verwendet. Falls die übergreifende Festlegung gilt, dass ISIK-Basisprofile bei Referenzen zu nutzen sind, dann sollen die Basisprofile ISIKPatient und ISiKKontaktGesundheitseinrichtung im CapabilityStatement und unter den zu unterstützenden / bestätigungsrelevanten Datenobjekten auftauchen

### Common Examples

??

### Drawbacks

Umsetzende Systeme müssen zusätzlich READ auf ISIKPatient und ISiKKontaktGesundheitseinrichtung implementieren

**Comment by alexzautke** [comment]
Da beide Felder als MS gekennzeichnet sind würde ich schon sagen, dass beide Referenzen auflösbar sein sollten, entsprechend unserer Absprachen zu ISiK Terminplanung und ISiK Dokumentenaustausch.

**Comment by f-peverali** [comment]
Ressourcen sind in CapabilityStatement hinzugefügt: https://github.com/gematik/spec-ISiK-Dokumentenaustausch/commit/cc6972d2b8d6c2808898a9218f0c67fd4521204e
